server: 
  id: 1
  host: 127.0.0.1
  port: 8001

DataFile: 
  name: data1
  n: 850
  dimision: 2

BeaverTripleFile: triple1

randomShareFile: randomshare1

rsignShareFile: rsignshare1

clusters: 4

tolerance: 1