server: 
  id: 2
  host: 127.0.0.1
  port: 8001

DataFile: 
  name: data2
  n: 150
  dimision: 2

BeaverTripleFile: triple2

randomShareFile: randomshare2

rsignShareFile: rsignshare2

clusters: 4

tolerance: 2048